[workspace]
resolver = "2"
members = [
    "aurora-core",      # 核心数据结构与trait
    "aurora-data",      # 数据采集模块
    "aurora-indicators",# 技术指标库
    "aurora-strategy",  # 策略逻辑
    "aurora-backtester",# 回测引擎
    "aurora-live"       # 实时模拟交易引擎
]
