# Aurora 配置文件示例 - 实时交易模式
# 
# 本配置文件展示了如何配置Aurora进行实时模拟交易
# 使用方法: aurora-live --config examples/live_config.toml

# ==================== 数据源配置 ====================
[data_source]
# 数据提供商
provider = "binance"

# WebSocket URL(用于实时数据流)
ws_url = "wss://stream.binance.com:9443"

# API超时时间(秒)
timeout = 30

# 最大重试次数
max_retries = 5

# 可选: API密钥(如果需要进行真实交易,而非模拟)
# api_key = "your_api_key"
# api_secret = "your_api_secret"

# ==================== 策略配置 ====================
[[strategies]]
name = "MA交叉实时策略"
strategy_type = "ma-crossover"
enabled = true

[strategies.parameters]
short = 10
long = 30

# ==================== 投资组合配置 ====================
[portfolio]
# 初始模拟资金
initial_cash = 10000.0

# 手续费率
commission = 0.001

# 滑点率
slippage = 0.0005

# 可选: 风险控制参数
max_position_size = 3000.0
max_positions = 2

# ==================== 日志配置 ====================
[logging]
# 实时交易建议使用info或debug级别
level = "info"

# 格式
format = "pretty"

# 可选: 输出到文件以便后续分析
# output = "live_trading.log"

# ==================== 实时交易配置 ====================
[live]
# 交易对符号 (必需)
symbol = "BTCUSDT"

# K线时间间隔
interval = "1m"

# 是否为模拟交易 (true=模拟, false=真实交易)
paper_trading = true
